package bm.b0b0b0.SoulGolem.model;

public enum FarmerState {
    MOVING_TO_TILL,
    TILLING,
    WAITING_SEEDS,
    PREPARE_FIELD,
    MOVING_TO_PLANT,
    PLANTING,
    WAIT_GROWTH,
    WANDERING,
    MOVING_TO_HARVEST,
    HARVESTING,
    MOVING_TO_CHEST,
    WAITING_CHEST,
    MOVING_TO_CRAFT,
    CRAFTING,
    MOVING_TO_TORCH,
    PLACING_TORCH,
    MOVING_TO_SEAT,
    PLACING_SEAT,
    SITTING,
    MOVING_TO_CLEAR,
    CLEARING,
    MOVING_TO_BONEMEAL,
    APPLYING_BONEMEAL,
    RESTING
}
